/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cards': typeof CardsRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/features': typeof FeaturesRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/transfers': typeof TransfersRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cards': typeof CardsRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/features': typeof FeaturesRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/transfers': typeof TransfersRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cards': typeof CardsRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/features': typeof FeaturesRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
  '/transfers': typeof TransfersRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/blog'
    | '/cards'
    | '/careers'
    | '/compliance'
    | '/confirm-email'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/deposit'
    | '/features'
    | '/invest'
    | '/investments'
    | '/loans'
    | '/notifications'
    | '/press'
    | '/privacy'
    | '/send'
    | '/settings'
    | '/store'
    | '/support'
    | '/terms'
    | '/transactions'
    | '/transfer'
    | '/transfers'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/blog'
    | '/cards'
    | '/careers'
    | '/compliance'
    | '/confirm-email'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/deposit'
    | '/features'
    | '/invest'
    | '/investments'
    | '/loans'
    | '/notifications'
    | '/press'
    | '/privacy'
    | '/send'
    | '/settings'
    | '/store'
    | '/support'
    | '/terms'
    | '/transactions'
    | '/transfer'
    | '/transfers'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/blog'
    | '/cards'
    | '/careers'
    | '/compliance'
    | '/confirm-email'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/deposit'
    | '/features'
    | '/invest'
    | '/investments'
    | '/loans'
    | '/notifications'
    | '/press'
    | '/privacy'
    | '/send'
    | '/settings'
    | '/store'
    | '/support'
    | '/terms'
    | '/transactions'
    | '/transfer'
    | '/transfers'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CardsRoute: typeof CardsRoute
  CareersRoute: typeof CareersRoute
  ComplianceRoute: typeof ComplianceRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  FeaturesRoute: typeof FeaturesRoute
  InvestRoute: typeof InvestRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoansRoute: typeof LoansRoute
  NotificationsRoute: typeof NotificationsRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  StoreRoute: typeof StoreRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  TransferRoute: typeof TransferRoute
  TransfersRoute: typeof TransfersRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CardsRoute: CardsRoute,
  CareersRoute: CareersRoute,
  ComplianceRoute: ComplianceRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  FeaturesRoute: FeaturesRoute,
  InvestRoute: InvestRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoansRoute: LoansRoute,
  NotificationsRoute: NotificationsRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  StoreRoute: StoreRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  TransferRoute: TransferRoute,
  TransfersRoute: TransfersRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
